using DEMP_RPG_API.Application.DTOs.Response.Character;
using DEMP_RPG_API.Domain.Entities;

namespace DEMP_RPG_API.Adapters.Mappers.User;

public class CharacterMapper
{
    public static GetCharacterSummaryResponse ToSummaryResponse(CharacterEntity character)
    {
        return new GetCharacterSummaryResponse(character.Id,
            character.UserId,
            character.RoomId,
            character.Name,
            character.Occupation,
            character.Age);
    }

    public static GetCharacterDetailResponseDTO ToDetailResponse(CharacterEntity character)
    {
        return new GetCharacterDetailResponseDTO(character.Id,
            character.UserId,
            character.RoomId,
            character.Name,
            character.Gender,
            character.Occupation,
            character.Residence,
            character.Age,
            character.Annotations,
            character.ItemIds
            );
    }

    public static GetCharacterFullResponseDTO ToFullResponse(CharacterEntity character,
        CharacterSkillsModernEntity characterSkills, CharacterStatsEntity characterStats)
    {
        return new GetCharacterFullResponseDTO(
            character.Id,
            characterStats.Id,
            characterSkills.Id,
            character.UserId,
            character.RoomId,
            character.Name,
            character.Gender,
            character.Occupation,
            character.Residence,
            character.Age,
            character.Annotations,
            character.ItemIds,
            characterStats.MaxAttributes,
            characterStats.Strength.Value,
            characterStats.Dexterity.Value,
            characterStats.Intelligence.Value,
            characterStats.Size.Value,
            characterStats.Power.Value,
            characterStats.Appearance.Value,
            characterStats.Education.Value,
            characterStats.HitPoints,
            characterStats.CurrentHp,
            characterStats.Luck,
            characterStats.Sanity,
            characterStats.CurrentSanity,
            characterStats.Move,
            characterStats.Build,
            characterStats.DamageBonus,
            characterStats.TemporaryInsanity,
            characterStats.IndefiniteSanity,
            characterStats.MajorWound,
            characterStats.Unconscious,
            characterStats.Dying,
            characterSkills.Accounting.Value,
            characterSkills.Anthropology.Value,
            characterSkills.Appraise.Value,
            characterSkills.Archaelogy.Value,
            characterSkills.ArtAndCraftSpecialization,
            characterSkills.ArtCraft.Value,
            characterSkills.Charm.Value,
            characterSkills.Climb.Value,
            characterSkills.ComputerUse.Value,
            characterSkills.CreditRating.Value,
            characterSkills.CthulhuMythos.Value,
            characterSkills.Disguise.Value,
            characterSkills.Dodge.Value,
            characterSkills.DriveAuto.Value,
            characterSkills.EletricRepair.Value,
            characterSkills.Eletronics.Value,
            characterSkills.FastTalk.Value,
            characterSkills.FightingAxe.Value,
            characterSkills.FightingBrawl.Value,
            characterSkills.FightingChainsaw.Value,
            characterSkills.FightingFlail.Value,
            characterSkills.FightingGarrote.Value,
            characterSkills.FightingSpear.Value,
            characterSkills.FightingSword.Value,
            characterSkills.FightingWhip.Value,
            characterSkills.FightingBow.Value,
            characterSkills.HandGun.Value,
            characterSkills.HeavyWeapons.Value,
            characterSkills.Flamethrower.Value,
            characterSkills.MachineGun.Value,
            characterSkills.RifleShotgun.Value,
            characterSkills.SubmachineGun.Value,
            characterSkills.FirstAid.Value,
            characterSkills.History.Value,
            characterSkills.Intimidate.Value,
            characterSkills.Jump.Value,
            characterSkills.LanguageOtherValue.Value,
            characterSkills.LanguageOtherSpecialization,
            characterSkills.LanguageOwn.Value,
            characterSkills.Law.Value,
            characterSkills.Listen.Value,
            characterSkills.LockSmith.Value,
            characterSkills.MechanicalRepair.Value,
            characterSkills.Medicine.Value,
            characterSkills.NaturalWorld.Value,
            characterSkills.Navigate.Value,
            characterSkills.Occult.Value,
            characterSkills.OperateHeavyMachinery.Value,
            characterSkills.Persuade.Value,
            characterSkills.PilotAirCraft.Value,
            characterSkills.Psychoanalysis.Value,
            characterSkills.Psychology.Value,
            characterSkills.Ride.Value,
            characterSkills.Astronomy.Value,
            characterSkills.Biology.Value,
            characterSkills.Botany.Value,
            characterSkills.Chemistry.Value,
            characterSkills.Cryptography.Value,
            characterSkills.Engineering.Value,
            characterSkills.Forensics.Value,
            characterSkills.Geology.Value,
            characterSkills.Mathematics.Value,
            characterSkills.Pharmacy.Value,
            characterSkills.Physics.Value,
            characterSkills.Zoology.Value,
            characterSkills.SleightOfHand.Value,
            characterSkills.SpotHidden.Value,
            characterSkills.Stealth.Value,
            characterSkills.Survival.Value,
            characterSkills.SurvivalSpecialization,
            characterSkills.Swim.Value,
            characterSkills.Throw.Value,
            characterSkills.Track.Value
            
            );
    }
}