using DEMP_RPG_API.Application.DTOs.Request.CharacterSkillsModern;
using DEMP_RPG_API.Application.DTOs.Response.CharacterSkillsModern;
using DEMP_RPG_API.Domain.Entities;
using DEMP_RPG_API.Domain.ValueObjects.Character;

namespace DEMP_RPG_API.Adapters.Mappers;

public class CharacterSkillsModernMapper
{
public static CharacterSkillsModernEntity ToEntity(
    CreateCharacterSkillsModernRequestDTO dto,
    Guid characterStatsId,
    int dexterity,
    int education)
{
    return CharacterSkillsModernEntity.Create(
        dto.CharacterId,
        characterStatsId,
        new AttributeSkillVO(dexterity),
        new AttributeSkillVO(education),
dto.Accounting.HasValue ? new AttributeSkillVO(dto.Accounting.Value) : null,
    dto.Anthropology.HasValue ? new AttributeSkillVO(dto.Anthropology.Value) : null,
    dto.Appraise.HasValue ? new AttributeSkillVO(dto.Appraise.Value) : null,
    dto.Archaelogy.HasValue ? new AttributeSkillVO(dto.Archaelogy.Value) : null,
    dto.ArtAndCraftSpecialization ?? string.Empty,
    dto.ArtCraft.HasValue ? new AttributeSkillVO(dto.ArtCraft.Value) : null,
    dto.Charm.HasValue ? new AttributeSkillVO(dto.Charm.Value) : null,
    dto.Climb.HasValue ? new AttributeSkillVO(dto.Climb.Value) : null,
    dto.ComputerUse.HasValue ? new AttributeSkillVO(dto.ComputerUse.Value) : null,
    dto.CreditRating.HasValue ? new AttributeSkillVO(dto.CreditRating.Value) : null,
    dto.CthulhuMythos.HasValue ? new AttributeSkillVO(dto.CthulhuMythos.Value) : null,
    dto.Disguise.HasValue ? new AttributeSkillVO(dto.Disguise.Value) : null,
    dto.Dodge.HasValue ? new AttributeSkillVO(dto.Dodge.Value) : null,
    dto.DriveAuto.HasValue ? new AttributeSkillVO(dto.DriveAuto.Value) : null,
    dto.EletricRepair.HasValue ? new AttributeSkillVO(dto.EletricRepair.Value) : null,
    dto.Eletronics.HasValue ? new AttributeSkillVO(dto.Eletronics.Value) : null,
    dto.FastTalk.HasValue ? new AttributeSkillVO(dto.FastTalk.Value) : null,
    dto.FightingAxe.HasValue ? new AttributeSkillVO(dto.FightingAxe.Value) : null,
    dto.FightingBrawl.HasValue ? new AttributeSkillVO(dto.FightingBrawl.Value) : null,
    dto.FightingChainsaw.HasValue ? new AttributeSkillVO(dto.FightingChainsaw.Value) : null,
    dto.FightingFlail.HasValue ? new AttributeSkillVO(dto.FightingFlail.Value) : null,
    dto.FightingGarrote.HasValue ? new AttributeSkillVO(dto.FightingGarrote.Value) : null,
    dto.FightingSpear.HasValue ? new AttributeSkillVO(dto.FightingSpear.Value) : null,
    dto.FightingSword.HasValue ? new AttributeSkillVO(dto.FightingSword.Value) : null,
    dto.FightingWhip.HasValue ? new AttributeSkillVO(dto.FightingWhip.Value) : null,
    dto.FightingBow.HasValue ? new AttributeSkillVO(dto.FightingBow.Value) : null,
    dto.HandGun.HasValue ? new AttributeSkillVO(dto.HandGun.Value) : null,
    dto.HeavyWeapons.HasValue ? new AttributeSkillVO(dto.HeavyWeapons.Value) : null,
    dto.Flamethrower.HasValue ? new AttributeSkillVO(dto.Flamethrower.Value) : null,
    dto.MachineGun.HasValue ? new AttributeSkillVO(dto.MachineGun.Value) : null,
    dto.RifleShotgun.HasValue ? new AttributeSkillVO(dto.RifleShotgun.Value) : null,
    dto.SubmachineGun.HasValue ? new AttributeSkillVO(dto.SubmachineGun.Value) : null,
    dto.FirstAid.HasValue ? new AttributeSkillVO(dto.FirstAid.Value) : null,
    dto.History.HasValue ? new AttributeSkillVO(dto.History.Value) : null,
    dto.Intimidate.HasValue ? new AttributeSkillVO(dto.Intimidate.Value) : null,
    dto.Jump.HasValue ? new AttributeSkillVO(dto.Jump.Value) : null,
    dto.LanguageOtherValue.HasValue ? new AttributeSkillVO(dto.LanguageOtherValue.Value) : null,
    dto.LanguageOtherSpecialization ?? string.Empty,
    dto.LanguageOwn.HasValue ? new AttributeSkillVO(dto.LanguageOwn.Value) : null,
    dto.Law.HasValue ? new AttributeSkillVO(dto.Law.Value) : null,
    dto.LibraryUse.HasValue ? new AttributeSkillVO(dto.LibraryUse.Value) : null,
    dto.Listen.HasValue ? new AttributeSkillVO(dto.Listen.Value) : null,
    dto.LockSmith.HasValue ? new AttributeSkillVO(dto.LockSmith.Value) : null,
    dto.MechanicalRepair.HasValue ? new AttributeSkillVO(dto.MechanicalRepair.Value) : null,
    dto.Medicine.HasValue ? new AttributeSkillVO(dto.Medicine.Value) : null,
    dto.NaturalWorld.HasValue ? new AttributeSkillVO(dto.NaturalWorld.Value) : null,
    dto.Navigate.HasValue ? new AttributeSkillVO(dto.Navigate.Value) : null,
    dto.Occult.HasValue ? new AttributeSkillVO(dto.Occult.Value) : null,
    dto.OperateHeavyMachinery.HasValue ? new AttributeSkillVO(dto.OperateHeavyMachinery.Value) : null,
    dto.Persuade.HasValue ? new AttributeSkillVO(dto.Persuade.Value) : null,
    dto.PilotAirCraft.HasValue ? new AttributeSkillVO(dto.PilotAirCraft.Value) : null,
    dto.Psychoanalysis.HasValue ? new AttributeSkillVO(dto.Psychoanalysis.Value) : null,
    dto.Psychology.HasValue ? new AttributeSkillVO(dto.Psychology.Value) : null,
    dto.Ride.HasValue ? new AttributeSkillVO(dto.Ride.Value) : null,
    dto.Astronomy.HasValue ? new AttributeSkillVO(dto.Astronomy.Value) : null,
    dto.Biology.HasValue ? new AttributeSkillVO(dto.Biology.Value) : null,
    dto.Botany.HasValue ? new AttributeSkillVO(dto.Botany.Value) : null,
    dto.Chemistry.HasValue ? new AttributeSkillVO(dto.Chemistry.Value) : null,
    dto.Cryptography.HasValue ? new AttributeSkillVO(dto.Cryptography.Value) : null,
    dto.Engineering.HasValue ? new AttributeSkillVO(dto.Engineering.Value) : null,
    dto.Forensics.HasValue ? new AttributeSkillVO(dto.Forensics.Value) : null,
    dto.Geology.HasValue ? new AttributeSkillVO(dto.Geology.Value) : null,
    dto.Mathematics.HasValue ? new AttributeSkillVO(dto.Mathematics.Value) : null,
    dto.Meteorology.HasValue ? new AttributeSkillVO(dto.Meteorology.Value) : null,
    dto.Pharmacy.HasValue ? new AttributeSkillVO(dto.Pharmacy.Value) : null,
    dto.SleightOfHand.HasValue ? new AttributeSkillVO(dto.SleightOfHand.Value) : null,
    dto.SpotHidden.HasValue ? new AttributeSkillVO(dto.SpotHidden.Value) : null,
    dto.Stealth.HasValue ? new AttributeSkillVO(dto.Stealth.Value) : null,
    dto.Survival.HasValue ? new AttributeSkillVO(dto.Survival.Value) : null,
    dto.SurvivalSpecialization ?? string.Empty,
    dto.Swim.HasValue ? new AttributeSkillVO(dto.Swim.Value) : null,
    dto.Throw.HasValue ? new AttributeSkillVO(dto.Throw.Value) : null,
    dto.Track.HasValue ? new AttributeSkillVO(dto.Track.Value) : null
    );
}
    public static void Update(CharacterSkillsModernEntity entity, UpdateCharacterSkillsModernRequestDTO dto)
    {
        entity.Update(
    dto.Accounting.HasValue ? new AttributeSkillVO(dto.Accounting.Value) : null,
    dto.Anthropology.HasValue ? new AttributeSkillVO(dto.Anthropology.Value) : null,
    dto.Appraise.HasValue ? new AttributeSkillVO(dto.Appraise.Value) : null,
    dto.Archaelogy.HasValue ? new AttributeSkillVO(dto.Archaelogy.Value) : null,
    dto.ArtAndCraftSpecialization,
    dto.ArtCraft.HasValue ? new AttributeSkillVO(dto.ArtCraft.Value) : null,
    dto.Charm.HasValue ? new AttributeSkillVO(dto.Charm.Value) : null,
    dto.Climb.HasValue ? new AttributeSkillVO(dto.Climb.Value) : null,
    dto.ComputerUse.HasValue ? new AttributeSkillVO(dto.ComputerUse.Value) : null,
    dto.CreditRating.HasValue ? new AttributeSkillVO(dto.CreditRating.Value) : null,
    dto.CthulhuMythos.HasValue ? new AttributeSkillVO(dto.CthulhuMythos.Value) : null,
    dto.Disguise.HasValue ? new AttributeSkillVO(dto.Disguise.Value) : null,
    dto.Dodge.HasValue ? new AttributeSkillVO(dto.Dodge.Value) : null,
    dto.DriveAuto.HasValue ? new AttributeSkillVO(dto.DriveAuto.Value) : null,
    dto.EletricRepair.HasValue ? new AttributeSkillVO(dto.EletricRepair.Value) : null,
    dto.Eletronics.HasValue ? new AttributeSkillVO(dto.Eletronics.Value) : null,
    dto.FastTalk.HasValue ? new AttributeSkillVO(dto.FastTalk.Value) : null,
    dto.FightingAxe.HasValue ? new AttributeSkillVO(dto.FightingAxe.Value) : null,
    dto.FightingBrawl.HasValue ? new AttributeSkillVO(dto.FightingBrawl.Value) : null,
    dto.FightingChainsaw.HasValue ? new AttributeSkillVO(dto.FightingChainsaw.Value) : null,
    dto.FightingFlail.HasValue ? new AttributeSkillVO(dto.FightingFlail.Value) : null,
    dto.FightingGarrote.HasValue ? new AttributeSkillVO(dto.FightingGarrote.Value) : null,
    dto.FightingSpear.HasValue ? new AttributeSkillVO(dto.FightingSpear.Value) : null,
    dto.FightingSword.HasValue ? new AttributeSkillVO(dto.FightingSword.Value) : null,
    dto.FightingWhip.HasValue ? new AttributeSkillVO(dto.FightingWhip.Value) : null,
    dto.FightingBow.HasValue ? new AttributeSkillVO(dto.FightingBow.Value) : null,
    dto.HandGun.HasValue ? new AttributeSkillVO(dto.HandGun.Value) : null,
    dto.HeavyWeapons.HasValue ? new AttributeSkillVO(dto.HeavyWeapons.Value) : null,
    dto.Flamethrower.HasValue ? new AttributeSkillVO(dto.Flamethrower.Value) : null,
    dto.MachineGun.HasValue ? new AttributeSkillVO(dto.MachineGun.Value) : null,
    dto.RifleShotgun.HasValue ? new AttributeSkillVO(dto.RifleShotgun.Value) : null,
    dto.SubmachineGun.HasValue ? new AttributeSkillVO(dto.SubmachineGun.Value) : null,
    dto.FirstAid.HasValue ? new AttributeSkillVO(dto.FirstAid.Value) : null,
    dto.History.HasValue ? new AttributeSkillVO(dto.History.Value) : null,
    dto.Intimidate.HasValue ? new AttributeSkillVO(dto.Intimidate.Value) : null,
    dto.Jump.HasValue ? new AttributeSkillVO(dto.Jump.Value) : null,
    dto.LanguageOtherValue.HasValue ? new AttributeSkillVO(dto.LanguageOtherValue.Value) : null,
    dto.LanguageOtherSpecialization,
    dto.LanguageOwn.HasValue ? new AttributeSkillVO(dto.LanguageOwn.Value) : null,
    dto.Law.HasValue ? new AttributeSkillVO(dto.Law.Value) : null,
    dto.LibraryUse.HasValue ? new AttributeSkillVO(dto.LibraryUse.Value) : null,
    dto.Listen.HasValue ? new AttributeSkillVO(dto.Listen.Value) : null,
    dto.LockSmith.HasValue ? new AttributeSkillVO(dto.LockSmith.Value) : null,
    dto.MechanicalRepair.HasValue ? new AttributeSkillVO(dto.MechanicalRepair.Value) : null,
    dto.Medicine.HasValue ? new AttributeSkillVO(dto.Medicine.Value) : null,
    dto.NaturalWorld.HasValue ? new AttributeSkillVO(dto.NaturalWorld.Value) : null,
    dto.Navigate.HasValue ? new AttributeSkillVO(dto.Navigate.Value) : null,
    dto.Occult.HasValue ? new AttributeSkillVO(dto.Occult.Value) : null,
    dto.OperateHeavyMachinery.HasValue ? new AttributeSkillVO(dto.OperateHeavyMachinery.Value) : null,
    dto.Persuade.HasValue ? new AttributeSkillVO(dto.Persuade.Value) : null,
    dto.PilotAirCraft.HasValue ? new AttributeSkillVO(dto.PilotAirCraft.Value) : null,
    dto.Psychoanalysis.HasValue ? new AttributeSkillVO(dto.Psychoanalysis.Value) : null,
    dto.Psychology.HasValue ? new AttributeSkillVO(dto.Psychology.Value) : null,
    dto.Ride.HasValue ? new AttributeSkillVO(dto.Ride.Value) : null,
    dto.Astronomy.HasValue ? new AttributeSkillVO(dto.Astronomy.Value) : null,
    dto.Biology.HasValue ? new AttributeSkillVO(dto.Biology.Value) : null,
    dto.Botany.HasValue ? new AttributeSkillVO(dto.Botany.Value) : null,
    dto.Chemistry.HasValue ? new AttributeSkillVO(dto.Chemistry.Value) : null,
    dto.Cryptography.HasValue ? new AttributeSkillVO(dto.Cryptography.Value) : null,
    dto.Engineering.HasValue ? new AttributeSkillVO(dto.Engineering.Value) : null,
    dto.Forensics.HasValue ? new AttributeSkillVO(dto.Forensics.Value) : null,
    dto.Geology.HasValue ? new AttributeSkillVO(dto.Geology.Value) : null,
    dto.Mathematics.HasValue ? new AttributeSkillVO(dto.Mathematics.Value) : null,
    dto.Meteorology.HasValue ? new AttributeSkillVO(dto.Meteorology.Value) : null,
    dto.Pharmacy.HasValue ? new AttributeSkillVO(dto.Pharmacy.Value) : null,
    dto.SleightOfHand.HasValue ? new AttributeSkillVO(dto.SleightOfHand.Value) : null,
    dto.SpotHidden.HasValue ? new AttributeSkillVO(dto.SpotHidden.Value) : null,
    dto.Stealth.HasValue ? new AttributeSkillVO(dto.Stealth.Value) : null,
    dto.Survival.HasValue ? new AttributeSkillVO(dto.Survival.Value) : null,
    dto.SurvivalSpecialization,
    dto.Swim.HasValue ? new AttributeSkillVO(dto.Swim.Value) : null,
    dto.Throw.HasValue ? new AttributeSkillVO(dto.Throw.Value) : null,
    dto.Track.HasValue ? new AttributeSkillVO(dto.Track.Value) : null
        );
    }

    public static GetCharacterSkillsModernResponseDTO ToResponseDTO(CharacterSkillsModernEntity entity)
    {
        return new GetCharacterSkillsModernResponseDTO(
            entity.Id,
            entity.CharacterId,
            entity.CharacterStatsId,
            entity.Accounting.Value,
            entity.Anthropology.Value,
            entity.Appraise.Value,
            entity.Archaelogy.Value,
            entity.ArtAndCraftSpecialization,
            entity.ArtCraft.Value,
            entity.Charm.Value,
            entity.Climb.Value,
            entity.ComputerUse.Value,
            entity.CreditRating.Value,
            entity.CthulhuMythos.Value,
            entity.Disguise.Value,
            entity.Dodge.Value,
            entity.DriveAuto.Value,
            entity.EletricRepair.Value,
            entity.Eletronics.Value,
            entity.FastTalk.Value,
            entity.FightingAxe.Value,
            entity.FightingBrawl.Value,
            entity.FightingChainsaw.Value,
            entity.FightingFlail.Value,
            entity.FightingGarrote.Value,
            entity.FightingSpear.Value,
            entity.FightingSword.Value,
            entity.FightingWhip.Value,
            entity.FightingBow.Value,
            entity.HandGun.Value,
            entity.HeavyWeapons.Value,
            entity.Flamethrower.Value,
            entity.MachineGun.Value,
            entity.RifleShotgun.Value,
            entity.SubmachineGun.Value,
            entity.FirstAid.Value,
            entity.History.Value,
            entity.Intimidate.Value,
            entity.Jump.Value,
            entity.LanguageOtherValue.Value,
            entity.LanguageOtherSpecialization,
            entity.LanguageOwn.Value,
            entity.Law.Value,
            entity.LibraryUse.Value,
            entity.Listen.Value,
            entity.LockSmith.Value,
            entity.MechanicalRepair.Value,
            entity.Medicine.Value,
            entity.NaturalWorld.Value,
            entity.Navigate.Value,
            entity.Occult.Value,
            entity.OperateHeavyMachinery.Value,
            entity.Persuade.Value,
            entity.PilotAirCraft.Value,
            entity.Psychoanalysis.Value,
            entity.Psychology.Value,
            entity.Ride.Value,
            entity.Astronomy.Value,
            entity.Biology.Value,
            entity.Botany.Value,
            entity.Chemistry.Value,
            entity.Cryptography.Value,
            entity.Engineering.Value,
            entity.Forensics.Value,
            entity.Geology.Value,
            entity.Mathematics.Value,
            entity.Meteorology.Value,
            entity.Pharmacy.Value,
            entity.SleightOfHand.Value,
            entity.SpotHidden.Value,
            entity.Stealth.Value,
            entity.Survival.Value,
            entity.SurvivalSpecialization,
            entity.Swim.Value,
            entity.Throw.Value,
            entity.Track.Value
        );
    }
}


