// <auto-generated />
using System;
using DEMP_RPG_API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEMP_RPG_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619235646_FixCharacterStatsPrimaryKey")]
    partial class FixCharacterStatsPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Annotations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("ItemIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Occupation")
                        .HasColumnType("int");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterSkillsModernEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Accounting")
                        .HasColumnType("int");

                    b.Property<int>("Anthropology")
                        .HasColumnType("int");

                    b.Property<int>("Appraise")
                        .HasColumnType("int");

                    b.Property<int>("Archaelogy")
                        .HasColumnType("int");

                    b.Property<string>("ArtAndCraftSpecialization")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ArtCraft")
                        .HasColumnType("int");

                    b.Property<int>("Astronomy")
                        .HasColumnType("int");

                    b.Property<int>("Biology")
                        .HasColumnType("int");

                    b.Property<int>("Botany")
                        .HasColumnType("int");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CharacterStatsId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Charm")
                        .HasColumnType("int");

                    b.Property<int>("Chemistry")
                        .HasColumnType("int");

                    b.Property<int>("Climb")
                        .HasColumnType("int");

                    b.Property<int>("ComputerUse")
                        .HasColumnType("int");

                    b.Property<int>("CreditRating")
                        .HasColumnType("int");

                    b.Property<int>("Cryptography")
                        .HasColumnType("int");

                    b.Property<int>("CthulhuMythos")
                        .HasColumnType("int");

                    b.Property<int>("Disguise")
                        .HasColumnType("int");

                    b.Property<int>("Dodge")
                        .HasColumnType("int");

                    b.Property<int>("DriveAuto")
                        .HasColumnType("int");

                    b.Property<int>("EletricRepair")
                        .HasColumnType("int");

                    b.Property<int>("Eletronics")
                        .HasColumnType("int");

                    b.Property<int>("Engineering")
                        .HasColumnType("int");

                    b.Property<int>("FastTalk")
                        .HasColumnType("int");

                    b.Property<int>("FightingAxe")
                        .HasColumnType("int");

                    b.Property<int>("FightingBow")
                        .HasColumnType("int");

                    b.Property<int>("FightingBrawl")
                        .HasColumnType("int");

                    b.Property<int>("FightingChainsaw")
                        .HasColumnType("int");

                    b.Property<int>("FightingFlail")
                        .HasColumnType("int");

                    b.Property<int>("FightingGarrote")
                        .HasColumnType("int");

                    b.Property<int>("FightingSpear")
                        .HasColumnType("int");

                    b.Property<int>("FightingSword")
                        .HasColumnType("int");

                    b.Property<int>("FightingWhip")
                        .HasColumnType("int");

                    b.Property<int>("FirstAid")
                        .HasColumnType("int");

                    b.Property<int>("Flamethrower")
                        .HasColumnType("int");

                    b.Property<int>("Forensics")
                        .HasColumnType("int");

                    b.Property<int>("Geology")
                        .HasColumnType("int");

                    b.Property<int>("HandGun")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeapons")
                        .HasColumnType("int");

                    b.Property<int>("History")
                        .HasColumnType("int");

                    b.Property<int>("Intimidate")
                        .HasColumnType("int");

                    b.Property<int>("Jump")
                        .HasColumnType("int");

                    b.Property<string>("LanguageOtherSpecialization")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("LanguageOtherValue")
                        .HasColumnType("int");

                    b.Property<int>("LanguageOwn")
                        .HasColumnType("int");

                    b.Property<int>("Law")
                        .HasColumnType("int");

                    b.Property<int>("LibraryUse")
                        .HasColumnType("int");

                    b.Property<int>("Listen")
                        .HasColumnType("int");

                    b.Property<int>("LockSmith")
                        .HasColumnType("int");

                    b.Property<int>("MachineGun")
                        .HasColumnType("int");

                    b.Property<int>("Mathematics")
                        .HasColumnType("int");

                    b.Property<int>("MechanicalRepair")
                        .HasColumnType("int");

                    b.Property<int>("Medicine")
                        .HasColumnType("int");

                    b.Property<int>("Meteorology")
                        .HasColumnType("int");

                    b.Property<int>("NaturalWorld")
                        .HasColumnType("int");

                    b.Property<int>("Navigate")
                        .HasColumnType("int");

                    b.Property<int>("Occult")
                        .HasColumnType("int");

                    b.Property<int>("OperateHeavyMachinery")
                        .HasColumnType("int");

                    b.Property<int>("Persuade")
                        .HasColumnType("int");

                    b.Property<int>("Pharmacy")
                        .HasColumnType("int");

                    b.Property<int>("PilotAirCraft")
                        .HasColumnType("int");

                    b.Property<int>("Psychoanalysis")
                        .HasColumnType("int");

                    b.Property<int>("Psychology")
                        .HasColumnType("int");

                    b.Property<int>("Ride")
                        .HasColumnType("int");

                    b.Property<int>("RifleShotgun")
                        .HasColumnType("int");

                    b.Property<int>("SleightOfHand")
                        .HasColumnType("int");

                    b.Property<int>("SpotHidden")
                        .HasColumnType("int");

                    b.Property<int>("Stealth")
                        .HasColumnType("int");

                    b.Property<int>("SubmachineGun")
                        .HasColumnType("int");

                    b.Property<int>("Survival")
                        .HasColumnType("int");

                    b.Property<string>("SurvivalSpecialization")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Swim")
                        .HasColumnType("int");

                    b.Property<int>("Throw")
                        .HasColumnType("int");

                    b.Property<int>("Track")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterSkillsModern", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterStatsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Appearance")
                        .HasColumnType("int");

                    b.Property<int>("Build")
                        .HasColumnType("int");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSanity")
                        .HasColumnType("int");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Dodge")
                        .HasColumnType("int");

                    b.Property<bool>("Dying")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<bool>("IndefiniteSanity")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<bool>("MajorWound")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxAttributes")
                        .HasColumnType("int");

                    b.Property<int>("Move")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Sanity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<bool>("TemporaryInsanity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Unconscious")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("CharacterStats", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SheetEnum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<string>("UserIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
