// <auto-generated />
using System;
using System.Collections.Generic;
using DEMP_RPG_API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DEMP_RPG_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625205712_RefactorCharacter")]
    partial class RefactorCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Annotations")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("ItemIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Occupation")
                        .HasColumnType("integer");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterSkillsModernEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterStatsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterSkillsModern", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterStatsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Build")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Luck")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAttributes")
                        .HasColumnType("integer");

                    b.Property<int>("Move")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CharacterStats", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SheetEnum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<Guid>>("UserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DEMP_RPG_API.Domain.Entities.CharacterStatsEntity", b =>
                {
                    b.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.PoolStatVo", "HitPoints", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Current")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterStatsEntityId");

                            b1.ToTable("CharacterStats");

                            b1.ToJson("HitPoints");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatsEntityId");
                        });

                    b.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.PoolStatVo", "Sanity", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Current")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterStatsEntityId");

                            b1.ToTable("CharacterStats");

                            b1.ToJson("Sanity");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatsEntityId");
                        });

                    b.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.BaseAttributeVo", "BaseAttributes", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatsEntityId")
                                .HasColumnType("uuid");

                            b1.HasKey("CharacterStatsEntityId");

                            b1.ToTable("CharacterStats");

                            b1.ToJson("BaseAttributes");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatsEntityId");

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Appearance", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Constitution", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Dexterity", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Education", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Intelligence", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Power", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Size", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.OwnsOne("DEMP_RPG_API.Domain.ValueObjects.Character.AttributeSkillVO", "Strength", b2 =>
                                {
                                    b2.Property<Guid>("BaseAttributeVoCharacterStatsEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer");

                                    b2.HasKey("BaseAttributeVoCharacterStatsEntityId");

                                    b2.ToTable("CharacterStats");

                                    b2.WithOwner()
                                        .HasForeignKey("BaseAttributeVoCharacterStatsEntityId");
                                });

                            b1.Navigation("Appearance")
                                .IsRequired();

                            b1.Navigation("Constitution")
                                .IsRequired();

                            b1.Navigation("Dexterity")
                                .IsRequired();

                            b1.Navigation("Education")
                                .IsRequired();

                            b1.Navigation("Intelligence")
                                .IsRequired();

                            b1.Navigation("Power")
                                .IsRequired();

                            b1.Navigation("Size")
                                .IsRequired();

                            b1.Navigation("Strength")
                                .IsRequired();
                        });

                    b.Navigation("BaseAttributes")
                        .IsRequired();

                    b.Navigation("HitPoints")
                        .IsRequired();

                    b.Navigation("Sanity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
