export const OCCUPATIONS = [
    { value: 1, label: "Contador" },
    { value: 2, label: "Acrobata" },
    { value: 3, label: "Ator/Atriz" },
    { value: 4, label: "Detetive de Agência" },
    { value: 5, label: "Alienista" },
    { value: 6, label: "Adestrador de Animais" },
    { value: 7, label: "Antiquário" },
    { value: 8, label: "Negociante de Antiguidades" },
    { value: 9, label: "Arqueólogo" },
    { value: 10, label: "Arquiteto" },
    { value: 11, label: "Artista" },
    { value: 12, label: "Atendente de Asilo" },
    { value: 13, label: "Assassino" },
    { value: 14, label: "Atleta" },
    { value: 15, label: "Autor" },
    { value: 16, label: "Aviador" },
    { value: 17, label: "Assaltante de Banco" },
    { value: 18, label: "Bartender" },
    { value: 19, label: "Caçador de Grandes Animais" },
    { value: 20, label: "Negociante de Livros" },
    { value: 21, label: "Contrabandista de Bebidas" },
    { value: 22, label: "Caçador de Recompensas" },
    { value: 23, label: "Boxeador/Lutador" },
    { value: 24, label: "Arrombador" },
    { value: 25, label: "Mordomo/Empregada" },
    { value: 26, label: "Motorista Particular" },
    { value: 27, label: "Clero" },
    { value: 28, label: "Vigarista" },
    { value: 29, label: "Vaqueiro" },
    { value: 30, label: "Artesão" },
    { value: 31, label: "Criminoso" },
    { value: 32, label: "Líder de Culto" },
    { value: 33, label: "Desprogramador" },
    { value: 34, label: "Designer" },
    { value: 35, label: "Diletante" },
    { value: 36, label: "Mergulhador" },
    { value: 37, label: "Médico" },
    { value: 38, label: "Vagabundo" },
    { value: 39, label: "Motorista" },
    { value: 40, label: "Editor" },
    { value: 41, label: "Funcionário Público Eleito" },
    { value: 42, label: "Engenheiro" },
    { value: 43, label: "Artista de Entretenimento" },
    { value: 44, label: "Explorador" },
    { value: 45, label: "Fazendeiro" },
    { value: 46, label: "Agente Federal" },
    { value: 47, label: "Receptador" },
    { value: 48, label: "Bombeiro" },
    { value: 49, label: "Correspondente Estrangeiro" },
    { value: 50, label: "Médico Legista" },
    { value: 51, label: "Falsificador" },
    { value: 52, label: "Jogador" },
    { value: 53, label: "Gângster" },
    { value: 54, label: "Comparsa de Gângster" },
    { value: 55, label: "Cavalheiro/Dama" },
    { value: 56, label: "Hacker" },
    { value: 57, label: "Andarilho" },
    { value: 58, label: "Auxiliar Hospitalar" },
    { value: 59, label: "Jornalista" },
    { value: 60, label: "Juiz" },
    { value: 61, label: "Assistente de Laboratório" },
    { value: 62, label: "Trabalhador Braçal" },
    { value: 63, label: "Advogado" },
    { value: 64, label: "Bibliotecário" },
    { value: 65, label: "Lenhador" },
    { value: 67, label: "Mecânico" },
    { value: 68, label: "Oficial Militar" },
    { value: 69, label: "Mineiro" },
    { value: 70, label: "Missionário" },
    { value: 71, label: "Alpinista" },
    { value: 72, label: "Curador de Museu" },
    { value: 73, label: "Músico" },
    { value: 74, label: "Enfermeiro" },
    { value: 75, label: "Ocultista" },
    { value: 76, label: "Aventureiro" },
    { value: 77, label: "Parapsicólogo" },
    { value: 78, label: "Farmacêutico" },
    { value: 79, label: "Fotógrafo" },
    { value: 80, label: "Fotojornalista" },
    { value: 81, label: "Piloto" },
    { value: 82, label: "Detetive de Polícia" },
    { value: 83, label: "Investigador Particular" },
    { value: 84, label: "Professor" },
    { value: 85, label: "Garimpeiro" },
    { value: 86, label: "Profissional do Sexo" },
    { value: 87, label: "Psiquiatra" },
    { value: 88, label: "Psicólogo" },
    { value: 89, label: "Repórter" },
    { value: 90, label: "Pesquisador" },
    { value: 91, label: "Marinheiro" },
    { value: 92, label: "Vendedor" },
    { value: 93, label: "Cientista" },
    { value: 94, label: "Secretário(a)" },
    { value: 95, label: "Comerciante" },
    { value: 96, label: "Contrabandista" },
    { value: 97, label: "Soldado" },
    { value: 98, label: "Espião" },
    { value: 99, label: "Marginal" },
    { value: 100, label: "Estudante" },
    { value: 101, label: "Dublê" },
    { value: 102, label: "Taxista" },
    { value: 103, label: "Capanga" },
    { value: 104, label: "Membro de Tribo" },
    { value: 105, label: "Agente Funerário" },
    { value: 106, label: "Ativista Sindical" },
    { value: 107, label: "Camareiro" },
    { value: 108, label: "Garçom/Garçonete" },
    { value: 109, label: "Trabalhador de Escritório" },
    { value: 110, label: "Zelote" },
    { value: 111, label: "Zelador de Zoológico" },
];