const SkillFields = 
[
    { key: "anthropology", label: "Antropologia" },
    { key: "fightingBow", label: "Armas de Fogo (Arco)" },
    { key: "heavyWeapons", label: "Armas de Fogo (Armas Pesadas)" },
    { key: "flamethrower", label: "Armas de Fogo (Lança-chamas)" },
    { key: "machineGun", label: "Armas de Fogo (Metralhadora)" },
    { key: "handGun", label: "Armas de Fogo (Pistola)" },
    { key: "rifleShotgun", label: "Armas de Fogo (Rifle/Espingarda)" },
    { key: "submachineGun", label: "Armas de Fogo (Submetralhadora)" },
    { key: "archaelogy", label: "Arqueologia" },
    { key: "throw", label: "Arremessar" },
    { key: "artCraft", label: "Arte e Ofício" },
    { key: "appraise", label: "Avaliação" },
    { key: "ride", label: "Cavalgar" },
    { key: "charm", label: "Charme" },
    { key: "lockSmith", label: "Chaveiro" },
    { key: "astronomy", label: "Ciência (Astronomia)" },
    { key: "biology", label: "Ciência (Biologia)" },
    { key: "botany", label: "Ciência (Botânica)" },
    { key: "cryptography", label: "Ciência (Criptografia)" },
    { key: "engineering", label: "Ciência (Engenharia)" },
    { key: "pharmacy", label: "Ciência (Farmácia)" },
    { key: "physics", label: "Ciência (Física)" },
    { key: "forensics", label: "Ciência (Forense)" },
    { key: "geology", label: "Ciência (Geologia)" },
    { key: "mathematics", label: "Ciência (Matemática)" },
    { key: "meteorology", label: "Ciência (Meteorologia)" },
    { key: "chemistry", label: "Ciência (Química)" },
    { key: "zoology", label: "Ciência (Zoologia)" },
    { key: "eletricRepair", label: "Conserto Elétrico" },
    { key: "mechanicalRepair", label: "Conserto Mecânico" },
    { key: "accounting", label: "Contabilidade" },
    { key: "law", label: "Direito" },
    { key: "driveAuto", label: "Dirigir" },
    { key: "disguise", label: "Disfarce" },
    { key: "eletronics", label: "Eletrônica" },
    { key: "spotHidden", label: "Encontrar" },
    { key: "climb", label: "Escalar" },
    { key: "listen", label: "Escutar" },
    { key: "dodge", label: "Esquivar" },
    { key: "stealth", label: "Furtividade" },
    { key: "history", label: "História" },
    { key: "intimidate", label: "Intimidação" },
    { key: "fastTalk", label: "Lábia" },
    { key: "languageOtherValue", label: "Língua (Outra)" },
    { key: "languageOwn", label: "Língua Nativa" },
    { key: "fightingBrawl", label: "Luta (Briga)" },
    { key: "fightingWhip", label: "Luta (Chicote)" },
    { key: "fightingSword", label: "Luta (Espada)" },
    { key: "fightingGarrote", label: "Luta (Garrote)" },
    { key: "fightingSpear", label: "Luta (Lança)" },
    { key: "fightingAxe", label: "Luta (Machado)" },
    { key: "fightingFlail", label: "Luta (Mangual)" },
    { key: "fightingChainsaw", label: "Luta (Motosserra)" },
    { key: "medicine", label: "Medicina" },
    { key: "cthulhuMythos", label: "Mitos de Cthulhu" },
    { key: "naturalWorld", label: "Mundo Natural" },
    { key: "swim", label: "Natação" },
    { key: "navigate", label: "Navegação" },
    { key: "creditRating", label: "Nível de Crédito" },
    { key: "occult", label: "Ocultismo" },
    { key: "operateHeavyMachinery", label: "Operar Máquinas Pesadas" },
    { key: "persuade", label: "Persuasão" },
    { key: "pilotAirCraft", label: "Pilotar (Aeronaves)" },
    { key: "sleightOfHand", label: "Prestidigitação" },
    { key: "firstAid", label: "Primeiros Socorros" },
    { key: "psychoanalysis", label: "Psicanálise" },
    { key: "psychology", label: "Psicologia" },
    { key: "track", label: "Rastrear" },
    { key: "jump", label: "Saltar" },
    { key: "survival", label: "Sobrevivência" },
    { key: "libraryUse", label: "Uso de Biblioteca" },
    { key: "computerUse", label: "Uso de Computador" },
]

export const sortedSkillFields = SkillFields.sort(function(a,b){
    if(a.label <b.label) { return -1; }
    if(a.label >b.label) { return 1; }
    return 0;
});