const SkillFields = 
[
    { key: "Anthropology", label: "Antropologia" },
    { key: "FightingBow", label: "Armas de Fogo (Arco)" },
    { key: "HeavyWeapons", label: "Armas de Fogo (Armas Pesadas)" },
    { key: "Flamethrower", label: "Armas de Fogo (Lança-chamas)" },
    { key: "MachineGun", label: "Armas de Fogo (Metralhadora)" },
    { key: "HandGun", label: "Armas de Fogo (Pistola)" },
    { key: "RifleShotgun", label: "Armas de Fogo (Rifle/Espingarda)" },
    { key: "SubmachineGun", label: "Armas de Fogo (Submetralhadora)" },
    { key: "Archaelogy", label: "Arqueologia" },
    { key: "Throw", label: "Arremessar" },
    { key: "ArtCraft", label: "Arte e Ofício" },
    { key: "Appraise", label: "Avaliação" },
    { key: "Ride", label: "Cavalgar" },
    { key: "Charm", label: "Charme" },
    { key: "LockSmith", label: "Chaveiro" },
    { key: "Astronomy", label: "Ciência (Astronomia)" },
    { key: "Biology", label: "Ciência (Biologia)" },
    { key: "Botany", label: "Ciência (Botânica)" },
    { key: "Cryptography", label: "Ciência (Criptografia)" },
    { key: "Engineering", label: "Ciência (Engenharia)" },
    { key: "Pharmacy", label: "Ciência (Farmácia)" },
    { key: "Physics", label: "Ciência (Física)" },
    { key: "Forensics", label: "Ciência (Forense)" },
    { key: "Geology", label: "Ciência (Geologia)" },
    { key: "Mathematics", label: "Ciência (Matemática)" },
    { key: "Meteorology", label: "Ciência (Meteorologia)" },
    { key: "Chemistry", label: "Ciência (Química)" },
    { key: "Zoology", label: "Ciência (Zoologia)" },
    { key: "EletricRepair", label: "Conserto Elétrico" },
    { key: "MechanicalRepair", label: "Conserto Mecânico" },
    { key: "Accounting", label: "Contabilidade" },
    { key: "Law", label: "Direito" },
    { key: "DriveAuto", label: "Dirigir" },
    { key: "Disguise", label: "Disfarce" },
    { key: "Eletronics", label: "Eletrônica" },
    { key: "SpotHidden", label: "Encontrar" },
    { key: "Climb", label: "Escalar" },
    { key: "Listen", label: "Escutar" },
    { key: "Dodge", label: "Esquivar" },
    { key: "Stealth", label: "Furtividade" },
    { key: "History", label: "História" },
    { key: "Intimidate", label: "Intimidação" },
    { key: "FastTalk", label: "Lábia" },
    { key: "LanguageOtherValue", label: "Língua (Outra)" },
    { key: "LanguageOwn", label: "Língua Nativa" },
    { key: "FightingBrawl", label: "Luta (Briga)" },
    { key: "FightingWhip", label: "Luta (Chicote)" },
    { key: "FightingSword", label: "Luta (Espada)" },
    { key: "FightingGarrote", label: "Luta (Garrote)" },
    { key: "FightingSpear", label: "Luta (Lança)" },
    { key: "FightingAxe", label: "Luta (Machado)" },
    { key: "FightingFlail", label: "Luta (Mangual)" },
    { key: "FightingChainsaw", label: "Luta (Motosserra)" },
    { key: "Medicine", label: "Medicina" },
    { key: "CthulhuMythos", label: "Mitos de Cthulhu" },
    { key: "NaturalWorld", label: "Mundo Natural" },
    { key: "Swim", label: "Natação" },
    { key: "Navigate", label: "Navegação" },
    { key: "CreditRating", label: "Nível de Crédito" },
    { key: "Occult", label: "Ocultismo" },
    { key: "OperateHeavyMachinery", label: "Operar Máquinas Pesadas" },
    { key: "Persuade", label: "Persuasão" },
    { key: "PilotAirCraft", label: "Pilotar (Aeronaves)" },
    { key: "SleightOfHand", label: "Prestidigitação" },
    { key: "FirstAid", label: "Primeiros Socorros" },
    { key: "Psychoanalysis", label: "Psicanálise" },
    { key: "Psychology", label: "Psicologia" },
    { key: "Track", label: "Rastrear" },
    { key: "Jump", label: "Saltar" },
    { key: "Survival", label: "Sobrevivência" },
    { key: "LibraryUse", label: "Uso de Biblioteca" },
    { key: "ComputerUse", label: "Uso de Computador" },
]

export const sortedSkillFields = SkillFields.sort(function(a,b){
    if(a.label <b.label) { return -1; }
    if(a.label >b.label) { return 1; }
    return 0;
});